# Please don't change the version manually.
version: 1

# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

durability:
  enchantable-items: ["DIAMOND_PICKAXE", "NETHERITE_PICKAXE", "DIAMOND_SHOVEL", "NETHERITE_SHOVEL"]

trench:
  enchantable-items: ["DIAMOND_PICKAXE", "NETHERITE_PICKAXE"]
  destroyable-items:
    [
      "COBBLESTONE", "STONE", "ANDESITE", "DIORITE", "GRANITE", "GRAVEL", "DIRT", "SANDSTONE", "RED_SANDSTONE",
      "COAL_ORE", "COPPER_ORE", "IRON_ORE", "REDSTONE_ORE", "LAPIS_ORE", "DIAMOND_ORE", "EMERALD_ORE",
      "NETHERRACK", "NETHER_QUARTZ_ORE", "SOUL_SAND", "BASALT", "BLACKSTONE",
      "WHITE_TERRACOTTA", "ORANGE_TERRACOTTA", "MAGENTA_TERRACOTTA", "LIGHT_BLUE_TERRACOTTA", "YELLOW_TERRACOTTA",
      "LIME_TERRACOTTA", "PINK_TERRACOTTA", "GRAY_TERRACOTTA", "LIGHT_GRAY_TERRACOTTA", "CYAN_TERRACOTTA",
      "PURPLE_TERRACOTTA", "BLUE_TERRACOTTA", "BROWN_TERRACOTTA", "GREEN_TERRACOTTA", "RED_TERRACOTTA",
      "BLACK_TERRACOTTA", "TERRACOTTA", "END_STONE", "SAND", "MOSSY_COBBLESTONE", "TUFF", "COBBLED_DEEPSLATE",
      "DEEPSLATE_COAL_ORE", "DEEPSLATE_IRON_ORE", "DEEPSLATE_COPPER_ORE", "DEEPSLATE_GOLD_ORE",
      "DEEPSLATE_REDSTONE_ORE", "DEEPSLATE_EMERALD_ORE", "DEEPSLATE_DIAMOND_ORE", "SMOOTH_BASALT", "CALCITE",
      "AMETHYST_BLOCK", "DEEPSLATE", "CRYING_OBSIDIAN", "OBSIDIAN", "MAGMA_BLOCK", "NETHER_GOLD_ORE",
      "GOLD_ORE", "GRASS_BLOCK"
    ]
titanAxe:
  enchantable-items: ["DIAMOND_AXE", "NETHERITE_AXE"]
  destroyable-items:
    [
      "OAK_LOG", "SPRUCE_LOG", "BIRCH_LOG", "JUNGLE_LOG", "ACACIA_LOG", "DARK_OAK_LOG", "CRIMSON_STEM", "WARPED_STEM",
      "OAK_LEAVES", "SPRUCE_LEAVES", "BIRCH_LEAVES", "JUNGLE_LEAVES", "ACACIA_LEAVES", "DARK_OAK_LEAVES", "NETHER_WART_BLOCK", "WARPED_WART_BLOCK",
      "MUSHROOM_STEM" , "RED_MUSHROOM_BLOCK", "BROWN_MUSHROOM_BLOCK","SHROOMLIGHT"
    ]
titanShovel:
  non-destroyable-items:
    [
      "BEDROCK", "CHEST", "SHULKER_BOX"
    ]